# Generated by Django 6.0.6 on 2026-06-27 19:32

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('slug', models.SlugField(help_text="e.g. 'ac-rentals'", verbose_name='Slug')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('seo_title', models.CharField(max_length=255, verbose_name='SEO Title')),
                ('description', models.TextField(verbose_name='Description')),
                ('seo_description', models.TextField(blank=True, verbose_name='SEO Description')),
                ('seo_keywords', models.JSONField(default=list, verbose_name='SEO Keywords')),
                ('main_image', models.ImageField(upload_to='catalog/main/', verbose_name='Main Image')),
                ('icon', models.CharField(blank=True, max_length=100, verbose_name='Icon (lucide name)')),
                ('features', models.JSONField(default=list, verbose_name='Feature Bullets')),
                ('blog_content', models.TextField(blank=True, verbose_name='Blog Content (Markdown)')),
                ('display_order', models.PositiveIntegerField(default=0, verbose_name='Display Order')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='tenants.tenant', verbose_name='Tenant')),
            ],
            options={
                'verbose_name': 'Service Category',
                'verbose_name_plural': 'Service Categories',
                'ordering': ['display_order', 'title'],
                'unique_together': {('tenant', 'slug')},
            },
        ),
        migrations.CreateModel(
            name='CategoryGallery',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('image', models.ImageField(upload_to='catalog/gallery/', verbose_name='Image')),
                ('caption', models.CharField(blank=True, max_length=255, verbose_name='Caption')),
                ('display_order', models.PositiveIntegerField(default=0, verbose_name='Display Order')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to='catalog.servicecategory')),
            ],
            options={
                'verbose_name': 'Gallery Image',
                'verbose_name_plural': 'Gallery Images',
                'ordering': ['display_order'],
            },
        ),
        migrations.CreateModel(
            name='ServiceReview',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('reviewer_name', models.CharField(max_length=150, verbose_name='Reviewer Name')),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='City')),
                ('rating', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Rating (1-5)')),
                ('text', models.TextField(verbose_name='Review Text')),
                ('review_date', models.CharField(blank=True, help_text="e.g. '2026-04'", max_length=10, verbose_name='Review Date')),
                ('is_visible', models.BooleanField(default=True, verbose_name='Visible')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='catalog.servicecategory')),
            ],
            options={
                'verbose_name': 'Service Review',
                'verbose_name_plural': 'Service Reviews',
                'ordering': ['-created_at'],
            },
        ),
    ]
