# Generated by Django 6.0.6 on 2026-06-27 19:32

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('subdomain', models.SlugField(help_text="e.g. 'najd-al-zain' → najd-al-zain.najdalzian.com", unique=True, verbose_name='Subdomain')),
                ('custom_domain', models.CharField(blank=True, help_text='Optional apex domain e.g. najdalzain.com', max_length=255, null=True, unique=True, verbose_name='Custom Domain')),
                ('name', models.CharField(max_length=255, verbose_name='Business Name')),
                ('tagline', models.CharField(blank=True, max_length=255, verbose_name='Tagline')),
                ('phone', models.CharField(max_length=30, verbose_name='Phone')),
                ('whatsapp', models.CharField(max_length=30, verbose_name='WhatsApp Number')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('address', models.TextField(blank=True, verbose_name='Address')),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='City')),
                ('geo_lat', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Latitude')),
                ('geo_lng', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Longitude')),
                ('logo', models.ImageField(upload_to='tenants/logos/', verbose_name='Logo')),
                ('favicon', models.ImageField(blank=True, upload_to='tenants/favicons/', verbose_name='Favicon')),
                ('theme', models.JSONField(default=dict, help_text='e.g. {"primary":"#5B2D4A","dark":"#3B1B30","gold_accent":"#D4AF37"}', verbose_name='Theme Colors')),
                ('analytics', models.JSONField(blank=True, default=dict, help_text='e.g. {"gtm_id":"GTM-XXXX","ga_id":"G-XXXX"}', verbose_name='Analytics')),
                ('language', models.CharField(choices=[('ar', 'Arabic'), ('en', 'English')], default='ar', max_length=2, verbose_name='Language')),
                ('direction', models.CharField(choices=[('rtl', 'Right to Left'), ('ltr', 'Left to Right')], default='rtl', max_length=3, verbose_name='Direction')),
                ('font_family', models.CharField(default='Tajawal', max_length=100, verbose_name='Font Family')),
                ('meta_title', models.CharField(blank=True, max_length=255, verbose_name='Meta Title')),
                ('meta_description', models.TextField(blank=True, verbose_name='Meta Description')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
            ],
            options={
                'verbose_name': 'Tenant',
                'verbose_name_plural': 'Tenants',
                'ordering': ['name'],
            },
        ),
    ]
