# Generated by Django 6.0.6 on 2026-06-27 19:32

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('title', models.CharField(max_length=255, verbose_name='Internal Title')),
                ('slug', models.SlugField(help_text="e.g. 'home', 'about', 'services'", verbose_name='URL Slug')),
                ('page_type', models.CharField(choices=[('home', 'Home'), ('services', 'Services'), ('about', 'About'), ('gallery', 'Gallery'), ('contact', 'Contact'), ('custom', 'Custom')], default='custom', max_length=20)),
                ('meta_title', models.CharField(blank=True, max_length=255)),
                ('meta_description', models.TextField(blank=True)),
                ('meta_keywords', models.JSONField(blank=True, default=list)),
                ('og_image', models.ImageField(blank=True, upload_to='pages/og/')),
                ('canonical_url', models.URLField(blank=True)),
                ('is_published', models.BooleanField(default=False)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Page',
                'verbose_name_plural': 'Pages',
                'ordering': ['display_order'],
                'unique_together': {('tenant', 'slug')},
            },
        ),
        migrations.CreateModel(
            name='ContentBlock',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('block_type', models.CharField(choices=[('hero', 'Hero Section'), ('services_grid', 'Services Grid'), ('about', 'About Us'), ('gallery', 'Gallery'), ('contact', 'Contact'), ('faq', 'FAQ'), ('testimonials', 'Testimonials'), ('text_banner', 'Text Banner'), ('custom_html', 'Custom HTML')], max_length=30)),
                ('content', models.JSONField(default=dict, verbose_name='Block Content')),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_visible', models.BooleanField(default=True)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocks', to='pages.page')),
            ],
            options={
                'verbose_name': 'Content Block',
                'verbose_name_plural': 'Content Blocks',
                'ordering': ['display_order'],
            },
        ),
        migrations.CreateModel(
            name='PageTab',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('label', models.CharField(max_length=100, verbose_name='Label')),
                ('icon', models.CharField(blank=True, max_length=100, verbose_name='Icon (lucide name)')),
                ('tab_type', models.CharField(choices=[('category_link', 'Category Link'), ('custom_url', 'Custom URL'), ('section_anchor', 'Section Anchor')], max_length=20)),
                ('link_value', models.CharField(help_text='Slug, full URL, or #anchor-id depending on tab_type', max_length=255, verbose_name='Link Value')),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tabs', to='pages.page')),
            ],
            options={
                'verbose_name': 'Page Tab',
                'verbose_name_plural': 'Page Tabs',
                'ordering': ['display_order'],
            },
        ),
    ]
